<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vrifier_slider</name>
   <tag></tag>
   <elementGuidId>754eb94e-fca7-4dfb-a08b-ef3801f0e9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='captcha__frame__bottom']/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.slider</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba8676a2-28ba-43fc-94a5-558a2a56d15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>c6fbf728-148c-4ec7-ad9b-c15ff6cb8299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captcha__frame__bottom&quot;)/div[@class=&quot;sliderContainer sliderContainer_active&quot;]/div[@class=&quot;slider&quot;]</value>
      <webElementGuid>26044317-0d6b-4d4e-846f-7dcdb23e5331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_groupe-sncf.com/iframe</value>
      <webElementGuid>dd1a1228-87ac-411f-989d-2acda6c0c7ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='captcha__frame__bottom']/div[2]/div[4]</value>
      <webElementGuid>2b48f86c-5377-4d46-b604-8922389dd391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vérifier'])[1]/preceding::div[5]</value>
      <webElementGuid>8bd5bc46-7ab1-4280-8667-575ee0958890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vous surfez et cliquez à une vitesse surhumaine'])[1]/preceding::div[7]</value>
      <webElementGuid>da9757d8-d351-442f-a3be-db6df2cc2a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
      <webElementGuid>53fdfb4b-143a-4805-b161-e750c97e14d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
