<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>8c008a76-c466-4e94-9c57-6a2f81590233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;DataDome CAPTCHA&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;DataDome CAPTCHA&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>24973d0f-ae9f-4f0e-a067-35b9db7ee138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAivO0C5PyxAwAsoRr4A%3D%3D&amp;hash=CF023EBD8B8F7948A964105BD76C50&amp;cid=vysV~fGwbBKO6VyB5aeOkSIN6I615k0Cc~YF8JQpjG~Aze9aoW7O9qP96lt1g~vsVh7T0MG8zwTL473anM59DP_zjrNAZ1dQ6o8SMboKCHwi8AbWrjgfAi~2dmzN5n5~&amp;t=fe&amp;referer=https%3A%2F%2Fwww.groupe-sncf.com%2Ffr%2Fgroupe%2Femploi&amp;s=48310&amp;e=0f081fcfad0a26248b8a255f9125d1a30a12cdc83384ef342f3f40d5dcccd758&amp;dm=cd</value>
      <webElementGuid>5a1debf7-49b1-4f23-b7eb-24b7141475d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-scripts allow-same-origin allow-forms</value>
      <webElementGuid>69299a81-a5fa-48c4-99b4-aa964afffcbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DataDome CAPTCHA</value>
      <webElementGuid>4845b9bd-366b-4d94-afad-7f662f923757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>deae55e8-dc69-4391-ab6b-cd1b6e00eb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3524f22d-8a7f-41c9-910f-46fb001dd2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>575594db-0a73-4c97-8740-b5b049c5771b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b0296c88-8051-4260-a21a-007899d54a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>33e016db-37d9-4b9e-8fdb-f4623a0f1aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/iframe[1]</value>
      <webElementGuid>99a94281-ed20-4e8f-bf7b-a606c17294e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2bb7f94f-b77e-4c3a-a312-3ecc1c9e7cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAivO0C5PyxAwAsoRr4A%3D%3D&amp;hash=CF023EBD8B8F7948A964105BD76C50&amp;cid=vysV~fGwbBKO6VyB5aeOkSIN6I615k0Cc~YF8JQpjG~Aze9aoW7O9qP96lt1g~vsVh7T0MG8zwTL473anM59DP_zjrNAZ1dQ6o8SMboKCHwi8AbWrjgfAi~2dmzN5n5~&amp;t=fe&amp;referer=https%3A%2F%2Fwww.groupe-sncf.com%2Ffr%2Fgroupe%2Femploi&amp;s=48310&amp;e=0f081fcfad0a26248b8a255f9125d1a30a12cdc83384ef342f3f40d5dcccd758&amp;dm=cd' and @title = 'DataDome CAPTCHA']</value>
      <webElementGuid>3b98aeef-31c5-4aaa-a15a-b398955446a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
